name: Build and Deploy
on:
  push:
  workflow_dispatch:
env:
  IMAGE_NAME: ghcr.io/ghetto05/ghettogpt
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      run: |
        # Construct tag with build number
        if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
          BASE_TAG="latest"
        else
          BASE_TAG="dev"
        fi

        TAG="${BASE_TAG}-build-${GITHUB_RUN_NUMBER}"

        echo "Tagging image as: $TAG"

        docker build -t $IMAGE_NAME:$TAG .
        docker push $IMAGE_NAME:$TAG

        # Push 'latest' tag only for master branch (optional)
        if [[ "$BASE_TAG" == "latest" ]]; then
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
        fi
    - name: Call Portainer webhook to trigger prod deploy
      if: success() && github.ref == 'refs/heads/master'
      run: |
        curl -X POST https://portainer.ghetto05.com/api/stacks/webhooks/1272d1df-5736-4fa2-b0d8-70e6e588ad86 # prod instance
    - name: Call Portainer webhook to trigger dev deploy
      if: success() && github.ref != 'refs/heads/master'
      run: |
        curl -X POST https://portainer.ghetto05.com/api/stacks/webhooks/bb5093a0-2769-4ed4-a4de-bfc3d4d63c8f # dev instance
