name: Build and Deploy

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/ghetto05/ghettogpt
  TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        VERSION_TAG=build-${{ github.run_number }}
        echo "Version tag: $VERSION_TAG"
        docker build \
          -t $IMAGE_NAME:$VERSION_TAG -t $IMAGE_NAME:latest .
        
        docker push $IMAGE_NAME:$VERSION_TAG
        docker push $IMAGE_NAME:latest

    - name: Call Portainer webhook to trigger deploy
      if: success() && github.ref == 'refs/heads/master'
      run: |
        curl -X POST https://portainer.ghetto05.com/api/stacks/webhooks/something # prod instance

    - name: Call Portainer webhook to trigger dev deploy
      if: success() && github.ref != 'refs/heads/master'
      run: |
        curl -X POST https://portainer.ghetto05.com/api/stacks/webhooks/somethingelse # dev instance
