name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/ghetto05/ghettogpt
  TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        VERSION_TAG=build-${{ github.run_number }}
        echo "Version tag: $VERSION_TAG"
        echo "${{ secrets.GITHUB_TOKEN }}"

        docker build \
          -t $IMAGE_NAME:$VERSION_TAG -t $IMAGE_NAME:latest .
        
        docker push $IMAGE_NAME:$VERSION_TAG
        docker push $IMAGE_NAME:latest

    - name: Call Portainer webhook to trigger deploy
      if: success()
      run: |
        # curl -X POST https://portainer.ghetto05.com/api/stacks/webhooks/fa8d4fae-8340-4092-86d3-7dbd2a13d32b